"Name: \TY:/IWBEP/CL_MGW_RT_DEF_BADI\IN:/IWBEP/IF_MGW_CORE_SRV_RUNTIME\ME:CLEANUP\SE:BEGIN\EI
ENHANCEMENT 0 ZGATEWAY_BEPSP10READENTITY.
*BTBOUNDY IW_BEP-SP10
  IF mo_runtime IS NOT BOUND.
    EXIT.
  ENDIF.
ENDENHANCEMENT.
